"""empty message

Revision ID: 22402bbdd154
Revises: e20fffa9db13
Create Date: 2020-08-12 20:03:38.392112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22402bbdd154'
down_revision = 'e20fffa9db13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cards', ['cardId'])
    op.create_unique_constraint(None, 'game', ['gameId'])
    op.create_foreign_key('fk_game_current_player_id', 'game', 'player', ['currentPlayerId'], ['playerId'], use_alter=True)
    op.create_unique_constraint('unique_player', 'player', ['gameId', 'playerName'])
    op.create_unique_constraint(None, 'player', ['playerId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_constraint('unique_player', 'player', type_='unique')
    op.drop_constraint('fk_game_current_player_id', 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='unique')
    op.drop_constraint(None, 'cards', type_='unique')
    # ### end Alembic commands ###
