"""empty message

Revision ID: 5eb079bfa0d9
Revises: 86012e51ffaa
Create Date: 2020-09-08 23:08:37.931254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb079bfa0d9'
down_revision = '86012e51ffaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'game', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='unique')
    # ### end Alembic commands ###
