"""empty message

Revision ID: 6f784e61cbc3
Revises: 
Create Date: 2020-08-15 19:43:46.584877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f784e61cbc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_card',
    sa.Column('actionCardId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('actionType', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('actionCardId')
    )
    op.create_table('cash_card',
    sa.Column('cashCardId', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cashCardId')
    )
    op.create_table('game',
    sa.Column('gameId', sa.Integer(), nullable=False),
    sa.Column('gamePassCode', sa.String(), nullable=False),
    sa.Column('numberOfPlayers', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('currentPlayerId', sa.Integer(), nullable=True),
    sa.Column('numberOfTurnsPlayed', sa.Integer(), nullable=False),
    sa.Column('gameStatus', sa.Enum('WaitingToStart', 'InProgress', 'Completed', name='gamestatus'), nullable=False),
    sa.Column('createdUtcDate', sa.DateTime(), nullable=True),
    sa.Column('currentInPlayCardId', sa.Integer(), nullable=True),
    sa.Column('isPlayerTurnComplete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['currentInPlayCardId'], ['cards.cardId'], name='fk_game_card_id', use_alter=True),
    sa.ForeignKeyConstraint(['currentPlayerId'], ['player.playerId'], name='fk_game_current_player_id', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('gameId'),
    sa.UniqueConstraint('gameId'),
    sa.UniqueConstraint('gamePassCode')
    )
    op.create_table('properties_card',
    sa.Column('propertiesCardId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('primaryColourId', sa.Integer(), nullable=False),
    sa.Column('secondaryColourId', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('propertiesCardId')
    )
    op.create_table('properties_color',
    sa.Column('colorId', sa.Integer(), nullable=False),
    sa.Column('onePairRentPrice', sa.Integer(), nullable=False),
    sa.Column('twoPairRentPrice', sa.Integer(), nullable=False),
    sa.Column('threePairRentPrice', sa.Integer(), nullable=False),
    sa.Column('fourPairRentPrice', sa.Integer(), nullable=False),
    sa.Column('numberNeededToCompleteSet', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('colorId')
    )
    op.create_table('rent_card',
    sa.Column('rentCardId', sa.Integer(), nullable=False),
    sa.Column('primaryColourId', sa.Integer(), nullable=False),
    sa.Column('secondaryColourId', sa.Integer(), nullable=True),
    sa.Column('payee', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rentCardId')
    )
    op.create_table('cards',
    sa.Column('cardId', sa.Integer(), nullable=False),
    sa.Column('cardType', sa.Enum('Properties', 'Cash', 'Rent', 'Action', name='cardtypes'), nullable=True),
    sa.Column('propertiesCardId', sa.Integer(), nullable=True),
    sa.Column('cashCardId', sa.Integer(), nullable=True),
    sa.Column('rentId', sa.Integer(), nullable=True),
    sa.Column('actionId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actionId'], ['action_card.actionCardId'], ),
    sa.ForeignKeyConstraint(['cashCardId'], ['cash_card.cashCardId'], ),
    sa.ForeignKeyConstraint(['propertiesCardId'], ['properties_card.propertiesCardId'], ),
    sa.ForeignKeyConstraint(['rentId'], ['rent_card.rentCardId'], ),
    sa.PrimaryKeyConstraint('cardId'),
    sa.UniqueConstraint('cardId')
    )
    op.create_table('player',
    sa.Column('playerId', sa.Integer(), nullable=False),
    sa.Column('playerPassCode', sa.String(), nullable=False),
    sa.Column('gameId', sa.Integer(), nullable=False),
    sa.Column('playerName', sa.String(), nullable=True),
    sa.Column('playerGameOrder', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gameId'], ['game.gameId'], ),
    sa.PrimaryKeyConstraint('playerId'),
    sa.UniqueConstraint('gameId', 'playerName', name='unique_player'),
    sa.UniqueConstraint('playerId')
    )
    op.create_table('rent_transaction',
    sa.Column('rentTransactionId', sa.Integer(), nullable=False),
    sa.Column('gameId', sa.Integer(), nullable=True),
    sa.Column('transactionStatus', sa.Enum('WaitingToStart', 'InProgress', 'Completed', name='gamestatus'), nullable=False),
    sa.Column('payee', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gameId'], ['game.gameId'], ),
    sa.PrimaryKeyConstraint('rentTransactionId'),
    sa.UniqueConstraint('rentTransactionId')
    )
    op.create_table('game_cards',
    sa.Column('gameId', sa.Integer(), nullable=False),
    sa.Column('cardId', sa.Integer(), nullable=False),
    sa.Column('playerId', sa.Integer(), nullable=True),
    sa.Column('cardStatus', sa.Enum('IsNotDrawn', 'IsOnHand', 'IsPlayedOnPropertyPile', 'IsDiscarded', 'IsPlayedOnCashPile', name='gamecardstatus'), nullable=False),
    sa.Column('isCardRightSideUp', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cardId'], ['cards.cardId'], ),
    sa.ForeignKeyConstraint(['gameId'], ['game.gameId'], ),
    sa.ForeignKeyConstraint(['playerId'], ['player.playerId'], ),
    sa.PrimaryKeyConstraint('gameId', 'cardId')
    )
    op.create_table('rent_payee_transaction',
    sa.Column('rentPayeeTransactionId', sa.Integer(), nullable=False),
    sa.Column('rentTransactionId', sa.Integer(), nullable=True),
    sa.Column('playerId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playerId'], ['player.playerId'], ),
    sa.ForeignKeyConstraint(['rentTransactionId'], ['rent_transaction.rentTransactionId'], ),
    sa.PrimaryKeyConstraint('rentPayeeTransactionId'),
    sa.UniqueConstraint('rentPayeeTransactionId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rent_payee_transaction')
    op.drop_table('game_cards')
    op.drop_table('rent_transaction')
    op.drop_table('player')
    op.drop_table('cards')
    op.drop_table('rent_card')
    op.drop_table('properties_color')
    op.drop_table('properties_card')
    op.drop_table('game')
    op.drop_table('cash_card')
    op.drop_table('action_card')
    # ### end Alembic commands ###
