"""empty message

Revision ID: 77cda94cbc3a
Revises: 7c8867de44e6
Create Date: 2020-08-30 17:31:27.955122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77cda94cbc3a'
down_revision = '7c8867de44e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cards', ['cardId'])
    op.create_unique_constraint(None, 'game', ['gameId'])
    op.create_foreign_key('fk_game_card_id', 'game', 'cards', ['currentInPlayCardId'], ['cardId'], use_alter=True)
    op.create_foreign_key('fk_game_current_player_id', 'game', 'player', ['currentPlayerId'], ['playerId'], ondelete='CASCADE', use_alter=True)
    op.create_unique_constraint(None, 'player', ['playerId'])
    op.create_unique_constraint(None, 'rent_payee_transaction', ['rentPayeeTransactionId'])
    op.create_unique_constraint(None, 'rent_transaction', ['rentTransactionId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rent_transaction', type_='unique')
    op.drop_constraint(None, 'rent_payee_transaction', type_='unique')
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_constraint('fk_game_current_player_id', 'game', type_='foreignkey')
    op.drop_constraint('fk_game_card_id', 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='unique')
    op.drop_constraint(None, 'cards', type_='unique')
    # ### end Alembic commands ###
