"""empty message

Revision ID: 86012e51ffaa
Revises: c04ff7721653
Create Date: 2020-09-08 22:44:03.997588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86012e51ffaa'
down_revision = 'c04ff7721653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cards', ['cardId'])
    op.create_unique_constraint(None, 'game', ['gameId'])
    op.create_foreign_key('fk_game_card_id', 'game', 'cards', ['currentInPlayCardId'], ['cardId'], use_alter=True)
    op.add_column('game_turn', sa.Column('gameTurn', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_game_current_player_id', 'game_turn', 'player', ['currentPlayerId'], ['playerId'], ondelete='CASCADE', use_alter=True)
    op.create_unique_constraint(None, 'player', ['playerId'])
    op.create_unique_constraint(None, 'rent_payee_transaction', ['rentPayeeTransactionId'])
    op.create_unique_constraint(None, 'rent_transaction', ['rentTransactionId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rent_transaction', type_='unique')
    op.drop_constraint(None, 'rent_payee_transaction', type_='unique')
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_constraint('fk_game_current_player_id', 'game_turn', type_='foreignkey')
    op.drop_column('game_turn', 'gameTurn')
    op.drop_constraint('fk_game_card_id', 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='unique')
    op.drop_constraint(None, 'cards', type_='unique')
    # ### end Alembic commands ###
