"""empty message

Revision ID: ab47be0a9ec4
Revises: 26f11923cc7c
Create Date: 2020-08-14 00:05:00.514449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab47be0a9ec4'
down_revision = '26f11923cc7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('currentInPlayCardId', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('isPlayerTurnComplete', sa.Boolean(), nullable=False))
    op.create_foreign_key('fk_game_card_id', 'game', 'cards', ['currentInPlayCardId'], ['cardId'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_game_card_id', 'game', type_='foreignkey')
    op.drop_column('game', 'isPlayerTurnComplete')
    op.drop_column('game', 'currentInPlayCardId')
    # ### end Alembic commands ###
