"""empty message

Revision ID: b5f6118f04bb
Revises: 
Create Date: 2020-07-25 13:51:19.543717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f6118f04bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_card',
    sa.Column('actionCardId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('actionType', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('actionCardId')
    )
    op.create_table('cash_card',
    sa.Column('cashCardId', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cashCardId')
    )
    op.create_table('game',
    sa.Column('gameId', sa.String(), nullable=False),
    sa.Column('numberOfPlayers', sa.Integer(), nullable=False),
    sa.Column('currentPlayer', sa.Integer(), nullable=True),
    sa.Column('numberOfTurnsPlayed', sa.Integer(), nullable=False),
    sa.Column('gameStatus', sa.Enum('WaitingToStart', 'InProgress', 'Completed', name='gamestatus'), nullable=False),
    sa.PrimaryKeyConstraint('gameId'),
    sa.UniqueConstraint('gameId')
    )
    op.create_table('properties_card',
    sa.Column('propertiesCardId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('primaryColourId', sa.Integer(), nullable=False),
    sa.Column('secondaryColourId', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('propertiesCardId')
    )
    op.create_table('properties_color',
    sa.Column('colorId', sa.Integer(), nullable=False),
    sa.Column('onePairRentPrice', sa.Integer(), nullable=False),
    sa.Column('twoPairRentPrice', sa.Integer(), nullable=False),
    sa.Column('threePairRentPrice', sa.Integer(), nullable=False),
    sa.Column('fourPairRentPrice', sa.Integer(), nullable=False),
    sa.Column('numberNeededToCompleteSet', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('colorId')
    )
    op.create_table('rent_card',
    sa.Column('rentCardId', sa.Integer(), nullable=False),
    sa.Column('primaryColourId', sa.Integer(), nullable=False),
    sa.Column('secondaryColourId', sa.Integer(), nullable=True),
    sa.Column('payee', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rentCardId')
    )
    op.create_table('cards',
    sa.Column('cardId', sa.Integer(), nullable=False),
    sa.Column('cardType', sa.Enum('Properties', 'Cash', 'Rent', 'Action', name='cardtypes'), nullable=True),
    sa.Column('propertiesCardId', sa.Integer(), nullable=True),
    sa.Column('cashCardId', sa.Integer(), nullable=True),
    sa.Column('rentId', sa.Integer(), nullable=True),
    sa.Column('actionId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actionId'], ['action_card.actionCardId'], ),
    sa.ForeignKeyConstraint(['cashCardId'], ['cash_card.cashCardId'], ),
    sa.ForeignKeyConstraint(['propertiesCardId'], ['properties_card.propertiesCardId'], ),
    sa.ForeignKeyConstraint(['rentId'], ['rent_card.rentCardId'], ),
    sa.PrimaryKeyConstraint('cardId'),
    sa.UniqueConstraint('cardId')
    )
    op.create_table('player',
    sa.Column('playerId', sa.Integer(), nullable=False),
    sa.Column('playerPassCode', sa.String(), nullable=False),
    sa.Column('gameId', sa.String(), nullable=True),
    sa.Column('playerName', sa.String(), nullable=True),
    sa.Column('playerGameOrder', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gameId'], ['game.gameId'], ),
    sa.PrimaryKeyConstraint('playerId'),
    sa.UniqueConstraint('playerId'),
    sa.UniqueConstraint('playerPassCode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    op.drop_table('cards')
    op.drop_table('rent_card')
    op.drop_table('properties_color')
    op.drop_table('properties_card')
    op.drop_table('game')
    op.drop_table('cash_card')
    op.drop_table('action_card')
    # ### end Alembic commands ###
